name: fedodo_micro
description: Microblogging with Fedodo

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  activitypub: ^1.2.5
  fedodo_general: ^1.8.3

  flutter_html: ^3.0.0-beta.1
  metadata_fetch: ^0.4.1
  url_launcher: ^6.1.8
  intl: ^0.18.0
  infinite_scroll_pagination: ^3.2.0
  cached_network_image: ^3.2.3
  html: ^0.15.3
  photo_view: ^0.14.0
  emoji_picker_flutter: ^1.5.4
  shared_preferences: ^2.0.17
  jwt_decoder: ^2.0.1
  font_awesome_flutter: ^10.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: packages/fedodo_general/fonts/Roboto/Roboto-Regular.ttf
        - asset: packages/fedodo_general/fonts/Roboto/Roboto-Black.ttf
    - family: NotoColorEmoji
      fonts:
        - asset: packages/fedodo_general/fonts/NotoColorEmoji-Regular.ttf
    - family: Righteous
      fonts:
        - asset: packages/fedodo_general/fonts/Righteous-Regular.ttf
  uses-material-design: true

  assets:
    - assets/