name: fedodo_micro
description: Microblogging with Fedodo

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.17
  oauth2_client: ^3.0.0
  http: ^0.13.5
  flutter_html: ^3.0.0-beta.1
  font_awesome_flutter: ^10.3.0
  metadata_fetch: ^0.4.1
  url_launcher: ^6.1.8
  timeago: ^3.3.0
  intl: ^0.18.0
  share_plus: ^7.0.1
  infinite_scroll_pagination: ^3.2.0
  flutter_vibrate: ^1.3.0
  cached_network_image: ^3.2.3
  jwt_decoder: ^2.0.1
  flutter_guid: ^0.3.1
  html: ^0.15.3
  easy_sidemenu: ^0.4.1+1
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Righteous
      fonts:
        - asset: fonts/Righteous-Regular.ttf
  uses-material-design: true

  assets:
    - assets/