name: BuildDev

on:
  workflow_dispatch:
  push:
    branches: [ dev ]

env:
  VERSION: 0.1.${{ github.run_number }}
  FLUTTER_VERSION: "3.7.12"

jobs:
  BuildApk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Flutter
        uses: britannio/action-install-flutter@main
#        with:
#          version: ${{ env.FLUTTER_VERSION }}

      - run: flutter build apk --build-name=${{ env.VERSION }} --build-number=${{ github.run_number }}
        working-directory: ./

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: apk
          path: ./build/app/outputs/flutter-apk/app-release.apk

  BuildWeb:
    runs-on: ubuntu-latest

    steps:
      - uses: Fedodo/Fedodo.Pipelines/BuildContainerFlutter@main
        with:
          DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
          REPO: "fedodo.ui.micro"
          TAG_PREFIX: "dev_"

      # Deploy to dev cluster
      - uses: Fedodo/Fedodo.Pipelines/DeployContainer@main
        with:
          KUBECTL_CONFIG: ${{ secrets.KUBECTL_CONFIG }}
          VALUES_FILE: "./Kubernetes/values.yaml"
          MICROSERVICE: "fedodo_ui_micro"
          REPO: "fedodo.ui.micro"